services:
  api:
    build: ./api
    volumes:
      - ./database.db:/app/database.db
    networks:
      - honkingversion
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.honkingversion-api.rule=Host(`api.honkingversion.runfoo.run`)"
      - "traefik.http.routers.honkingversion-api.entrypoints=websecure"
      - "traefik.http.routers.honkingversion-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.honkingversion-api.loadbalancer.server.port=8000"
    restart: unless-stopped

  web:
    build:
      context: ./web
      args:
        NEXT_PUBLIC_API_URL: https://api.honkingversion.runfoo.run
        INTERNAL_API_URL: http://api:8000
    environment:
      - NEXT_PUBLIC_API_URL=https://api.honkingversion.runfoo.run
      - INTERNAL_API_URL=http://api:8000
      - NEXTAUTH_SECRET=ee38f08185c0cc5962b0de17d0dc553621dd27e54ea6aa49fc2134e84cbddb20
    depends_on:
      - api
    networks:
      - honkingversion
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.honkingversion.rule=Host(`honkingversion.runfoo.run`)"
      - "traefik.http.routers.honkingversion.entrypoints=websecure"
      - "traefik.http.routers.honkingversion.tls.certresolver=letsencrypt"
      - "traefik.http.services.honkingversion.loadbalancer.server.port=3000"
    restart: unless-stopped

networks:
  honkingversion:
  traefik:
    external: true
